NZSL-73 Added extra content to signbank export
ackama/nzsl-share pull request #600
Opened 2023-12-11 03:57 UTC by hopkincame

This PR adds more info to the signbank export based on Micky's comments on NZSL-75. This includes the following:

- Contributer username
- Contributer email address
- Time of sign upload
- Agree and disagree counts
- Comments (including both the username and the comment itself)

2023-12-13 21:31 UTC, joshmcarthur requested changes
I've made a couple of recommendations here

2023-12-13 23:49 UTC, joshmcarthur requested changes
One small thing left I think!

2023-12-13 23:49 UTC, joshmcarthur commented on app/services/signbank_export.rb
> +      FULL OUTER JOIN sign_comments ON signs.id = sign_comments.sign_id AND sign_comments.removed = false AND sign_comments.display = true
```suggestion
      FULL OUTER JOIN sign_comments ON signs.id = sign_comments.sign_id AND sign_comments.removed = false AND sign_comments.display = true AND sign_comments.folder_id IS NULL
```

Comments can be made in the context of a folder, and shouldn't be included here either.

2023-12-14 01:19 UTC, joshmcarthur approved these changes
I expect there to be a bit of iteration on this, but this is a solid start 👍 Nice work!

2023-12-14 01:47 UTC, brooke-m approved these changes

2023-12-14 02:06 UTC, merged